[package]
name = "recorder"
version = "0.1.0"
license = "MIT"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
